# database.yml

development:
  adapter: postgresql
  database: development
  username: root
  password: starwars
  host: localhost

production:
  adapter: postgresql
  database: development
  username: root
  password: starwars
  host: localhost